

services:
  frontend:
    build:
      context: ../../React/zus-project-client
      dockerfile: Dockerfile
   # multi-stage that ends on nginx

    container_name: zus-frontend
    depends_on:
      - backend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/ssl/local:/etc/ssl/local:ro
      - ./uploads:/usr/share/nginx/uploads:ro



  backend:
    build: .
    container_name: zus-backend
    volumes:
      - ./data:/app/data
      - ./uploads:/app/uploads
    #ports:
      #- "8080:8080"
    expose:
      - "8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/zusProjectServer
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: secret
      FILE_UPLOADS_DIR: /app/uploads


  db:
    image: mysql:8.0
    container_name: zus-mysql
    restart: always
    environment:
      MYSQL_DATABASE: zusProjectServer
      MYSQL_ROOT_PASSWORD: secret
    ports:
    - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-uroot", "-psecret" ]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  mysql_data:

