spring:
  datasource:
    url: jdbc:mysql://localhost/zusProjectServer?createDatabaseIfNotExist=true
    #url: jdbc:mysql://db:3306/zusProjectServer?createDatabaseIfNotExist=true
    username: root
    password:
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
    show-sql: true
    #properties:
      #hibernate: org.hibernate.dialect.MySQL8Dialect

  jackson:
    mapper:
      accept-case-insensitive-enums: true

server:
  address: 0.0.0.0
  port: 8080

debug: true