spring:
  datasource:
    url: jdbc:mysql://localhost/zusProjectServer?createDatabaseIfNotExist=true
    #url: jdbc:mysql://db:3306/zusProjectServer?createDatabaseIfNotExist=true
    username: root
    password:
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
    show-sql: true
    #properties:
      #hibernate: org.hibernate.dialect.MySQL8Dialect
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

file:
  upload-dir: uploads

  jackson:
    mapper:
      accept-case-insensitive-enums: true

server:
  address: 0.0.0.0
  port: 8080

debug: false

logging:
  level:
    root: DEBUG
    com.zaxxer.hikari: INFO
  pattern:
    console: "%d{HH:mm:ss.SSS} %-5level %logger{36} - %msg%n"